name: triggering_code

on: 
   push:  
        paths:
            - 'speechInteraction/**'
            - '!**/README.md'

jobs:
    test:
      runs-on: [ubuntu-latest]
      steps:
        - name: Get Token
          id: get_workflow_token
          uses: tibdex/github-app-token@v1
          with:
            private_key: ${{ secrets.ICUB_TECH_CODE_KEY }}
            app_id: ${{ secrets.ICUB_TECH_CODE_ID }}
            repository: icub-tech-iit/code
            
        - name: Repository dispatch to code
          uses: peter-evans/repository-dispatch@v1
          env:
            GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          with:
            token: ${{ env.GITHUB_APPS_TOKEN }}
            repository: icub-tech-iit/code
            event-type: repository_trigger
            client-payload: '{"type": "repository_trigger", "img_list": "speech"}'

